name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Build nginx-quic with BoringSSL
        run: |
          git clone https://boringssl.googlesource.com/boringssl
          cd boringssl
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ../..
          hg clone -b quic https://hg.nginx.org/nginx-quic
          cd nginx-quic
          ./auto/configure --with-debug --with-http_v3_module         \
                           --with-cc-opt="-I../boringssl/include"     \
                           --with-ld-opt="-L../boringssl/build/ssl    \
                                          -L../boringssl/build/crypto"
          make
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: nginx-quic
          path: nginx-quic
