name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          choco install -y cmake
          choco install -y nasm
          choco install -y perl
      - name: Build nginx-quic with BoringSSL
        run: |
          git clone https://boringssl.googlesource.com/boringssl
          cd boringssl
          mkdir build
          cd build
          cmake -G "Visual Studio 15 2017 Win64" ..
          cmake --build . --config Release
          cd ../..
          hg clone -b quic https://hg.nginx.org/nginx-quic
          cd nginx-quic
          set OPENSSL_DIR=c:/boringssl/build
          set PATH=%PATH%;C:\boringssl\build\bin
          nmake
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: nginx-quic
          path: nginx-quic
